steps:
- id: "Rodando testes"
  name: "gcr.io/cloud-builders/go"
  args: ["test"]
  dir: "./desafio_go_kube/src/"
  env: ["PROJECT_ROOT=main", "GOPATH=./desafio_go_kube/src/"]

- id: "Gerando imagem e salvando no container registry"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio-go-kube", "desafio_go_kube/"]

images: ["gcr.io/$PROJECT_ID/desafio-go-kube"]
