steps:
- id: "Rodando testes"
  name: "gcr.io/cloud-builders/go"
  args: ["test"]
  dir: "./desafio_go/src/"
  env: ["PROJECT_ROOT=main", "GOPATH=./desafio_go/src/"]

- id: "Gerando imagem e salvando no container registry"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/codeeducation", "desafio_go/"]

images: ["gcr.io/$PROJECT_ID/codeeducation"]
